// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6mlCT2PYJ2mtUk3mA1x28y0Wgx6z6shI',
    appId: '1:143610990485:android:7df0206b5ffe603bea709c',
    messagingSenderId: '143610990485',
    projectId: 'the-green-house-p9',
    storageBucket: 'the-green-house-p9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVvqGk4bBRVG5cyh6q4d8y0ZsAg7tXjaA',
    appId: '1:143610990485:ios:0cfef3065c79bc45ea709c',
    messagingSenderId: '143610990485',
    projectId: 'the-green-house-p9',
    storageBucket: 'the-green-house-p9.appspot.com',
    androidClientId: '143610990485-7u7raemkgu2trbjenrguufof33tcv215.apps.googleusercontent.com',
    iosClientId: '143610990485-b7jcval3u4j2sk3m6910cpuskv0q6n71.apps.googleusercontent.com',
    iosBundleId: 'lk.sliit.u24.u1.u1.p9.thegreenhouse',
  );
}
