name: thegreenhouse
description: "A state-of-the-art greenhouse system developed and maintained by Bhanuka Bandara, Ruvindi Jayasooriya Muditha Pasan, Yashara Wanigasekara, Safak Ahamed, and Sandini Imesha for University 1st Year 1st Semester Group Project."
publish_to: 'none'
version: 3.0.0+1
environment:
  sdk: ^3.7.0-183.0.dev

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  intl: ^0.20.1
  flutter_floating_bottom_bar: ^1.2.1+1
  lottie: ^3.1.3
  http: ^1.2.2
  flutter_svg: ^2.0.16

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo.png
    - assets/AI/Hi.json
    - assets/AI/AI-Read.json
    - assets/AI/AI-Think.json
    - assets/AI/AI-Write.json
    - assets/test.jpg
    - assets/plant@good.svg
    - assets/plant@bad.svg