name: thegreenhouse
description: "A state-of-the-art greenhouse system developed and maintained by Bhanuka Bandara, Ruvindi Jayasooriya Muditha Pasan, Yashara Wanigasekara, Safak Ahamed, and Sandini Imesha for University 1st Year 1st Semester Group Project."
publish_to: 'none'
version: 3.0.0+1
environment:
  sdk: ^3.7.0-183.0.dev

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_dotenv: ^5.2.1
  intl: ^0.20.1
  flutter_floating_bottom_bar: ^1.2.1+1
  lottie: ^3.1.3
  appwrite: ^13.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/logo.png
    - assets/AI/Hi.json