name: thegreenhouse
description: "A state-of-the-art greenhouse system"
publish_to: 'none'

version: 1.5.0+10

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  package_info_plus: ^8.0.2
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  google_sign_in: ^6.2.1
  auto_size_text: ^3.0.0
  lottie: ^3.1.2
  flutter_svg: ^2.0.10+1
  cloud_firestore: ^5.4.2
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1


flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/haventAssigned.json
    - assets/AI-Hi.json
    - assets/plant@good.svg
    - assets/plant@bad.svg
    - assets/alerts_loading.json
  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa.ttf
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true